### ISSUE TITLE
政令指定都市の市のみの名称を選択すると検索結果がヒットしない

### ISSUE THREAD

**Issue by erikka-22** [cfj-afterpillsearch/search-backend#14]
政令指定都市で、市区の名称(例:札幌市中央区)を選択すると該当する結果が返ってきますが、市のみの名称(例:札幌市)を選択すると結果が返ってきません。

・政令指定都市では市のみの名称は選択肢として表示しない
もしくは
・政令指定都市で市のみの名称を選択して検索した場合、その市に属する全ての区にある医療機関情報を返す

のどちらかで実装されるとよいかと思いました！

**Comment by osappy** [comment]
>・政令指定都市では市のみの名称は選択肢として表示しない
市のみでの検索は大量の検索結果が出てくることが予想され、市のみでの検索は行わないことにした。
フロントエンドで対応するので、本チケットはクローズする。
