### ISSUE TITLE
医療機関・薬局検索のresultsの数のデフォルト値を200に上げる

### ISSUE THREAD

**Issue by tanimuranaomichi** [cfj-afterpillsearch/search-backend#19]
200が適切かどうかは、スプレッドシートを確認しておく

**Comment by osappy** [comment]
このCSVファイルを使ってください。
https://cfj.slack.com/archives/C05AGEKGUSU/p1693904400645039

**Comment by erikka-22** [comment]
フロントにページング処理を実装する方針に変更
